# File: .github/workflows/trigger-ci-pipeline.yml

name: Trigger CI Pipeline

on:
  push:
    branches: [main, develop]
    paths-ignore: ['**.md', 'docs/**']

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Send Repository Dispatch Event
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.CI_PAT }}
          repository: your-org/ci-orchestration-repo
          event-type: app-code-change
          client-payload: '{
            "repository": "${{ github.repository }}",
            "ref": "${{ github.ref }}",
            "sha": "${{ github.sha }}"
          }'